package com.pluginforge.world;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Pure source/static deep audit for world self-heal gates.
 * Always regenerated by WorldScenarioRunner.
 */
class WorldHooksDeepAuditTest {
    private static final String ARTIFACT = "storyweaver";

    @Test
    void deepWorldHooks() throws Exception {
        Path javaRoot = Path.of("src/main/java");
        assertTrue(Files.isDirectory(javaRoot), "src/main/java missing");
        String domain = readNamed(javaRoot, "DomainService.java");
        String listener = readNamed(javaRoot, "CoreListener.java");
        String menu = readNamed(javaRoot, "MenuListener.java");
        String discord = readNamed(javaRoot, "DiscordWebhookClient.java");
        String yaml = readNamed(javaRoot, "YamlStorage.java");
        boolean grave = ARTIFACT.contains("grave");
        boolean echo = ARTIFACT.contains("echo");

        if (grave) {
            assertTrue(domain.contains("serializeItems") || !domain.contains("onPlayerDeath"),
                    "grave DomainService must serializeItems when onPlayerDeath exists");
            assertTrue(listener.contains("getDrops().clear()")
                            || !listener.contains("PlayerDeathEvent")
                            || !listener.contains("onPlayerDeath"),
                    "grave CoreListener must clear drops on death");
        } else {
            assertTrue(domain.contains("serializeItems") || !grave
                    || !domain.contains("onPlayerDeath"));
        }

        if (listener.contains("mirrorChat") || domain.contains("mirrorChat")) {
            assertTrue(listener.contains("runTask") || listener.contains("runTaskAsynchronously"),
                    "mirrorChat must be scheduled off async chat thread");
        }

        if (!menu.isBlank()) {
            assertTrue(menu.contains("MenuHolder") || !menu.contains("InventoryClickEvent"),
                    "MenuListener should use MenuHolder");
        }

        if (!discord.isBlank() && discord.contains("escape")) {
            assertTrue(discord.contains("\\n") || discord.contains("\\r"),
                    "Discord escape must handle newlines");
        }

        if (!yaml.isBlank()) {
            assertTrue(yaml.contains("getLong"), "YamlStorage must expose getLong");
        }

        if (echo) {
            assertTrue(domain.toLowerCase(Locale.ROOT).contains("lastmirror")
                            || domain.toLowerCase(Locale.ROOT).contains("debounce")
                            || domain.contains("// debounce")
                            || domain.contains("lastMirror"),
                    "echolink mirrorChat should debounce / lastMirror");
        }

        // UniversalBugCurriculum gates (always)
        assertTrue(listener.contains("ignoreCancelled = true")
                        || !listener.contains("@EventHandler"),
                "EventHandlers should use ignoreCancelled where appropriate");
        assertTrue(listener.contains("PlayerQuitEvent") || listener.contains("onQuit")
                        || listener.contains("onPlayerQuit"),
                "CoreListener should soft-cleanup on PlayerQuit");
        String mainPlugin = readNamed(javaRoot, findMain(javaRoot));
        if (!mainPlugin.isBlank()) {
            assertTrue(mainPlugin.contains("onDisable")
                            && (mainPlugin.contains("shutdown") || mainPlugin.contains("saveAll")),
                    "onDisable should shutdown services / save storage");
            assertTrue(mainPlugin.contains("saveDefaultConfig"),
                    "onEnable should call saveDefaultConfig");
        }
        String admin = readNamed(javaRoot, "AdminCommand.java");
        if (!admin.isBlank()) {
            assertTrue(!admin.contains(""Offline."") || admin.contains("admin.offline"),
                    "AdminCommand should use messages.yml for Offline");
        }
        String configYml = "";
        Path cfg = Path.of("src/main/resources/config.yml");
        if (Files.isRegularFile(cfg)) {
            configYml = Files.readString(cfg);
        }
        assertTrue(configYml.contains("language:") || configYml.isBlank(),
                "config.yml should declare language en|ru");
        String msgSvc = readNamed(javaRoot, "MessageService.java");
        if (!msgSvc.isBlank()) {
            assertTrue(msgSvc.contains("language") || msgSvc.contains("locale"),
                    "MessageService must respect language key");
        }
    }

    private static String findMain(Path javaRoot) throws Exception {
        try (Stream<Path> s = Files.walk(javaRoot)) {
            return s.filter(p -> {
                        try {
                            String t = Files.readString(p);
                            return t.contains("extends JavaPlugin");
                        } catch (Exception e) {
                            return false;
                        }
                    })
                    .map(p -> p.getFileName().toString())
                    .findFirst()
                    .orElse("ForgePlugin.java");
        }
    }

    private static String readNamed(Path javaRoot, String fileName) throws Exception {
        StringBuilder sb = new StringBuilder();
        try (Stream<Path> s = Files.walk(javaRoot)) {
            s.filter(p -> p.getFileName().toString().equals(fileName)).forEach(p -> {
                try { sb.append(Files.readString(p)); } catch (Exception ignored) {}
            });
        }
        return sb.toString();
    }
}
